import React from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';

const Success = () => {
  return (
    <>
      <Head>
        <title>Adam Sadowski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Successfully submitted form</h1>
      </div>
    </>
  );
};

export default Success;
